from .start import StartScreen as start
from .about import AboutScreen as about
from .loading import LoadingScreen as loading
from .auth import AuthScreen as auth
from .two_factor import TwoFactorScreen as two_factor
from .captcha import CaptchaScreen as captcha
from .game import GameScreen as game
from .game import ResultScreen as result
from .game import OverScreen as over
from .game import game_helper as game_helper